name: Deploy to Site

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

env:
  EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
  EC2_REPOSITORY: ${{ secrets.EC2_REPOSITORY }}
  EC2_USER: ${{ secrets.EC2_USER }}
  AWS_REGION: ap-northeast-2                   

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Pull Latest Code from webtoon-site
      run: |
        command_id=$(aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --instance-ids $EC2_INSTANCE_ID \
          --parameters commands="cd $EC2_REPOSITORY/site && sudo -u $EC2_USER git pull origin master" \
          --query "Command.CommandId" \
          --output text)

        echo "Command sent. Waiting for $command_id..."

        status="InProgress"
        while [[ "$status" == "InProgress" ]]; do
          status=$(aws ssm list-command-invocations \
            --command-id $command_id \
            --query "CommandInvocations[0].Status" \
            --output text)

          echo "..."
          sleep 1
        done
        
        echo "Command status: $status"

        if [[ "$status" != "Success" ]]; then
          echo "Command failed with status: $status"
          exit 1
        fi
          
    - name: Restart Gunicorn Service
      run: |
        command_id=$(aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --instance-ids $EC2_INSTANCE_ID \
          --parameters commands="sudo systemctl restart gunicorn" \
          --query "Command.CommandId" \
          --output text)

        echo "Restart command sent. Waiting for $command_id..."

        status="InProgress"
        while [[ "$status" == "InProgress" ]]; do
          status=$(aws ssm list-command-invocations \
            --command-id $command_id \
            --query "CommandInvocations[0].Status" \
            --output text)

          echo "..."
          sleep 1
        done
        
        echo "Command status: $status"

        if [[ "$status" != "Success" ]]; then
          echo "Restart command failed with status: $status"
          exit 1
        fi
